### ISSUE TITLE
How to run the simulator and agent on windows

### ISSUE THREAD

**Issue by yuqian-lu** [usnistgov/smstestbed#2]
Hi,

Thank you for sharing the testbed data, which significantly promoted the research on this direction.

I am new to MTConnect and NIST smstestbed, would you please provide some instructions on running the testbed data as simulator and MTConnect agent on windows system, local computer?

Much appreciated.

Michael

**Comment by tdh1** [comment]
Hello,

Thanks for the interest in the SMS Test Bed. Running the simulator with the NIST data is done using the same process as described at: http://mtcup.org/wiki/Installing_C%2B%2B_Agent_on_Ubuntu#Setup_a_configuration_directory.

The specific schema and devices.xml for the NIST data is available at: https://github.com/usnistgov/smstestbed/tree/master/mtconnect/agent.

An example of starting the simulator using the data from the GFAgie01 machine would look like:
`exec ruby /etc/mtconnect/adapter/run_scenario.rb -l -p 7878 /etc/mtconnect/adapter/data/GFAgie01-20160502-20160503.txt`

Our devices file includes all of our current publicly available machines. Therefore, a probe of your local agent will show all the machines even if your are running only one adapter simulator.

I hope this is enough to get you started. If not, we’re here to help.

Thank you,
Tom
